{% set name = "pyctcdecode" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyctcdecode-{{ version }}.tar.gz
  sha256: f3bcb313e43ca16a54938b3e77b0b375328653bba932668243db745fde513a2c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - hypothesis >=6.14,<7
    - numpy >=1.15.0,<2.0.0
    - pygtrie >=2.1,<3.0

test:
  imports:
    - pyctcdecode
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kensho-technologies/pyctcdecode
  summary: CTC beam search decoder for speech recognition.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    A fast and feature-rich CTC beam search decoder for speech recognition written in Python, 
    providing n-gram (kenlm) language model support similar to PaddlePaddle's decoder, but 
    incorporating many new features such as byte pair encoding and real-time decoding to 
    support models like Nvidia's 
    [Conformer-CTC](https://github.com/kensho-technologies/pyctcdecode/blob/main/tutorials/01_pipeline_nemo.ipynb) 
    or Facebook's 
    [Wav2Vec2](https://github.com/kensho-technologies/pyctcdecode/blob/main/tutorials/02_pipeline_huggingface.ipynb).


    PyPI: [https://pypi.org/project/pyctcdecode/](https://pypi.org/project/pyctcdecode/)

  doc_url: https://github.com/kensho-technologies/pyctcdecode
  dev_url: https://github.com/kensho-technologies/pyctcdecode

extra:
  recipe-maintainers:
    - sugatoray
